{
 "title": "Postgres_my",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values( pg_up,instance)" }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database is up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_up{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Whoami",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pg_static{instance=~\"$instance\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pg_static{instance=~\"$instance\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "% current/total connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(pg_stat_activity_count{instance=\"$instance\"}) / sum(pg_settings_max_connections)) * 100",
     "legendFormat": "total/all connection"
    }
   ]
  },
  {
   "title": "Dtabase size",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{instance=~\"$instance\",datname!=\"postgres\",datname!=\"ea\",datname!=\"template0\",datname!=\"template1\"}/1024/1024/1024",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Replication LAG",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_replication_lag{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{instance=~\"$instance\"})\n",
     "legendFormat": "Current connections"
    },
    {
     "expr": "sum(pg_settings_max_connections{instance=~\"$instance\"})",
     "legendFormat": "Max connections"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(pg_stat_activity_count{instance=~\"$instance\"}[$__interval])) /\nsum(pg_settings_max_connections{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Задержка репликации в мб",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_stat_replication_pg_wal_lsn_diff{instance=~\"$instance\"}/10000000"
    }
   ]
  },
  {
   "title": "Отставание репликации в секундах",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_replication_lag{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Transaction per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_calls{instance=~\"$instance\"}[1m]))/60"
    }
   ]
  },
  {
   "title": "Mean query time avg 1m by instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_mean_time_seconds{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sum connetctions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (state) (pg_stat_activity_count{instance=\"$instance\"}) ",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{instance=\"$instance\", datname!=\"postgres\", datname!=\"ea\", datname!=\"template0\", datname!=\"template1\",state=\"active\"}",
       "legendFormat": "{{datname}} {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Stats",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Rows" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_fetched{instance=\"$instance\"}[5m]) > 1000",
       "legendFormat": "{{datname}} SELECT (index scan)"
      },
      {
       "expr": "rate(pg_stat_database_tup_returned{instance=\"$instance\"}[5m]) > 1000",
       "legendFormat": "{{datname}} SELECT (table scan)"
      }
     ]
    },
    {
     "title": "Change Stats",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "Rows" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_inserted{instance=\"$instance\"}[5m]) > 1",
       "legendFormat": "{{datname}} INSERT"
      },
      {
       "expr": "rate(pg_stat_database_tup_updated{instance=\"$instance\"}[5m]) > 1",
       "legendFormat": "{{datname}} UPDATE"
      },
      {
       "expr": "rate(pg_stat_database_tup_deleted{instance=\"$instance\"}[5m]) > 1",
       "legendFormat": "{{datname}} DELETE"
      }
     ]
    },
    {
     "title": "Update data",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_updated{instance=~\"$instance\", datname!=\"postgres\", datname!=\"template0\", datname!=\"template1\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname!=\"postgres\", datname!=\"template0\", datname!=\"template1\"}[5m])",
       "legendFormat": "{{datname}} commits"
      },
      {
       "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname!=\"postgres\", datname!=\"template0\", datname!=\"template1\"}[5m])",
       "legendFormat": "{{datname}} rollbacks"
      }
     ]
    },
    {
     "title": "Fetch data (SELECT)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_fetched{instance=~\"$instance\", datname!=\"postgres\", datname!=\"template0\", datname!=\"template1\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Insert data",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_inserted{instance=~\"$instance\", datname!=\"postgres\", datname!=\"template0\", datname!=\"template1\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Return data",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_returned{instance=~\"$instance\", datname!=\"postgres\", datname!=\"template0\", datname!=\"template1\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Delete data",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_deleted{instance=~\"$instance\", datname!=\"postgres\", datname!=\"template0\", datname!=\"template1\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slowest transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_max_tx_duration{state='active', instance=~\"$instance\", datname!=\"postgres\", datname!=\"template0\", datname!=\"template1\", datname!=\"ea\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Lock Tables",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_locks_count{instance=\"$instance\"}",
       "legendFormat": "{{datname}} {{mode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers/Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hit Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_blks_hit{instance=\"$instance\"} / (pg_stat_database_blks_read{instance=\"$instance\"} + pg_stat_database_blks_hit{instance=\"$instance\"})",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Buffers (bgwriter)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_backend"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_alloc{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_alloc"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{instance=\"$instance\"}[5m])",
       "legendFormat": "backend_fsync"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_checkpoint"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_clean{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_clean"
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_conflicts{instance=\"$instance\", datname!=\"postgres\", datname!=\"template0\", datname!=\"template1\", datname!=\"datname\"}[5m])",
       "legendFormat": "{{datname}} conflicts"
      },
      {
       "expr": "irate(pg_stat_database_deadlocks{instance=\"$instance\", datname!=\"postgres\", datname!=\"template0\", datname!=\"template1\", datname!=\"datname\"}[5m])",
       "legendFormat": "{{datname}} deadlocks"
      }
     ]
    },
    {
     "title": "Temp File (Bytes)",
     "type": "graph",
     "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_temp_bytes{instance=\"$instance\",datname!=\"postgres\", datname!=\"template0\", datname!=\"template1\"}[5m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Checkpoint Stats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 39 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{instance=\"$instance\"}[5m])",
       "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
      },
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{instance=\"$instance\"}[5m])",
       "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
      }
     ]
    }
   ]
  }
 ]
}